use_frameworks!

target 'GGNObservable_Example' do
  pod 'GGNObservable', :path => '../'

  target 'GGNObservable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
